# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AALShqgXkvqYU6f__FrA22SMWmi2TXCJjNTO1m8XJ";
    path = fetchgit {
      url = "https://code.hexops.org/hexops/xcode-frameworks.git";
      rev = "8a1cfb373587ea4c9bb1468b7c986462d8d4e10e";
      hash = "sha256-b1Ay3GfBHwubnrGi4lflPiaqGfzWtABEbEiE8+ZTL90=";
    };
  }
  {
    name = "N-V-__8AANEmUgA6aZZZKbfNMv6DSs5In7CDFU6nInu_Y6aY";
    path = fetchzip {
      url = "https://codeload.github.com/google/wuffs-mirror-release-c/tar.gz/90e4d81a6a8b7b601e8e568da32a105d7f7705e5";
      hash = "sha256-IGZq1T10h6Y61999sW60sOw0YXQn5JAHRLywPawE6H0=";
      extension = "tar.gz";
    };
  }
  {
    name = "aro-0.0.0-JSD1Qi7QNgDnfcrdEJf82v3o6MhZySjYVrtdfEf3E4Se";
    path = fetchgit {
      url = "https://github.com/Vexu/arocc";
      rev = "5f5a050569a95ecc40a426f0c3666ae7ef987ede";
      hash = "sha256-f8Z0SXWx5Uia2TCMB5SUpcO8+xUnaWk32Oknva7xcxw=";
    };
  }
  {
    name = "cbor-1.2.0-RcQE_NtLAQCkBF-LFNB_XsGIycs6pjhCYicxEq0QzYfe";
    path = fetchgit {
      url = "https://github.com/neurocyte/cbor";
      rev = "8f37f71439f62b513b9d52a76d6af012395ee47c";
      hash = "sha256-Z+xTK/HhFjkdpUQkSPHoa2enpy6xCN9ASgtGBrT5cgI=";
    };
  }
  {
    name = "cmark_gfm-0.1.0-uQgTKymaFwDK0jVZszXfDtQtW6BnS44Bp0GS55TVBD4p";
    path = fetchgit {
      url = "https://github.com/kristoff-it/cmark-gfm";
      rev = "cd0aba87cc89f0c8aa9393e59505db271ea30239";
      hash = "sha256-YDxL2AZtuViib7D1BoR26bdTMtbuOM4b9NYUTqtJJRc=";
    };
  }
  {
    name = "flow_syntax-0.7.2-X8jOoeFgAQBquxUXx-h5g_xXQzcNAOtyz3M4fVUwgrOd";
    path = fetchgit {
      url = "https://github.com/neurocyte/flow-syntax";
      rev = "28d643c3fd8455faab0ea12383da9d6ddcbe9cb0";
      hash = "sha256-9kUdkBhJx00qzAoEN9sAfERBZW4JLmZcfl+Gx0iagm4=";
    };
  }
  {
    name = "known_folders-0.0.0-Fy-PJk7KAAC41mQXzmFyGa0Q7tvmQjatENkREa6Gc4zu";
    path = fetchgit {
      url = "https://github.com/ziglibs/known-folders";
      rev = "175f5596b3d2ee3c658282bb07885580895a0e73";
      hash = "sha256-gTnTyqkAAT5AYXxbG80ybiiRk+pOkm7dvqThcNWGmpo=";
    };
  }
  {
    name = "lsp_kit-0.1.0-bi_PL_kyDACVTEhLaMq2-PJx0MocqRyjXDAN0ybMUyQQ";
    path = fetchgit {
      url = "https://github.com/zigtools/lsp-kit";
      rev = "ec325a3c33d1da7708cf513355208f74d9560580";
      hash = "sha256-60F2BOCrl3CreQFmpH3HAz6zzxd3VgJ3iSEkP39gtgQ=";
    };
  }
  {
    name = "mime-3.0.0-zwmL--0gAAByELrj57sRm2EFBRzjKLFrMgHQcs7sFZev";
    path = fetchgit {
      url = "https://github.com/kristoff-it/mime";
      rev = "a2ed0cba3b1463217168034ffed8c1604e72598d";
      hash = "sha256-j/O/6pJg0hj3ytAMVBQwGjCRtaR+GYy8X7oqfIpuRi8=";
    };
  }
  {
    name = "scripty-0.1.0-LKK5OzcUAQDVndpJNPAm4eC_-G0HaXUdQejzb9X6C2vq";
    path = fetchgit {
      url = "https://github.com/kristoff-it/scripty";
      rev = "9c1e5903acd2a591f87f577b2ea08895e7168b9d";
      hash = "sha256-Lf4poXX5tdLV2UsmNVwdX5SHICX1ucsfgFLgKfTIPII=";
    };
  }
  {
    name = "superhtml-0.6.2-Y7MdPCZxJADwkXTXHmwQ0AKWKgbmQjJBnT7QTVqaX9Vp";
    path = fetchgit {
      url = "https://github.com/kristoff-it/superhtml";
      rev = "5ca7066c50b10c459aa6d1ad011bc37124c2d354";
      hash = "sha256-e/7OMTIGmSatHaRBgLB73UW1Hl2hLbqbsSZaXcd4sKU=";
    };
  }
  {
    name = "supermd-0.1.0-3Mco3CiXWABRpK_kiTdTuVJ7eZOm102_E8j5C6qyRh_2";
    path = fetchgit {
      url = "https://github.com/kristoff-it/supermd";
      rev = "4132146450f1ecbaa3fbd75cfeabccd754d6e716";
      hash = "sha256-lmRz6WLVJROhdtNe4n9Q33vik7wXg634ighq6sJoTNA=";
    };
  }
  {
    name = "tracy-0.0.0-4Xw-1pwwAABTfMgoDP1unCbZDZhJEfict7XCBGF6IdIn";
    path = fetchgit {
      url = "https://github.com/kristoff-it/tracy";
      rev = "67d2d89e351048c76fc6d161e0ac09d8a831dc60";
      hash = "sha256-BKo1bhua/u+f5Z//ailur5aSHZWp3GiC0iwmVLrGZkE=";
    };
  }
  {
    name = "translate_c-0.0.0-Q_BUWvP1BgCjAk6PWv5286tOlvzD9-X-NkuTzh0KxY0Q";
    path = fetchgit {
      url = "https://codeberg.org/ziglang/translate-c";
      rev = "7a1a9fdc4ab00835748a6657ecbb835e3d5d45f7";
      hash = "sha256-zdZ/it+/yNGfszHLqpXpi20Gkwm8fduMMs1/l9oaje8=";
    };
  }
  {
    name = "translate_c-1.0.0-Q_BUWo75BgBmrtWsRz9QVUZlzvsSUUe_IIXD9vmWguhX";
    path = fetchgit {
      url = "https://codeberg.org/ziglang/translate-c";
      rev = "42f630117deffd5318b4a6ceffbd366dd0af8cee";
      hash = "sha256-tdZ3u/G4UEqo5fpPZoVOjwx02sJRvKoHCx7/nqd+X0I=";
    };
  }
  {
    name = "tree_sitter-0.26.7-z0LhyKZw5DNYN1vvSVemWE5oXx6ViFRx1eD4_z6SN35-";
    path = fetchzip {
      url = "https://github.com/neurocyte/tree-sitter/releases/download/master-9edae3a2a86cc63e97c6bb78d5ffef4510a10606/source.tar.gz";
      hash = "sha256-oJQg+SL10BA4Kr+jOQKSuSY/l1LD7kt1fqpojJpNpvM=";
    };
  }
  {
    name = "wuffs-0.4.0-alpha.9+3837.20240914-3CHJgRMKAAAuMytwtlaBGjTMPVuDQSnCE3qMGg2NDTfr";
    path = fetchgit {
      url = "https://github.com/allyourcodebase/wuffs";
      rev = "6fd35cb51e90c4f69c64f3a2c28eb8aa36dc9c8b";
      hash = "sha256-+giQNQfQBJ8yG8lVvtJWmD5RxUs4xRfXwNtgKCoaHZc=";
    };
  }
  {
    name = "zeit-0.6.0-5I6bk3K6AgCFnc_9CN7KJjaeNJz1VuwP4DA7Gs9vgxuz";
    path = fetchgit {
      url = "https://github.com/rockorager/zeit";
      rev = "fdaad9c5884f41a3640c768f4f9fc116e763c321";
      hash = "sha256-YNQmVE2mZJ8T1MyGLVPht6fvEgSM7hmtDqfJGJ4tja8=";
    };
  }
  {
    name = "ziggy-0.1.0-kTg8v15ABgBGDedRmKfxGUWBxSxMBnEfYjazvZKVVrzP";
    path = fetchgit {
      url = "https://github.com/kristoff-it/ziggy";
      rev = "0fdd57cbb052e7aa5930b3ed960ea3450f9dc2b0";
      hash = "sha256-3AdwH5Na/v1iUVZJKk6JCoVvBhR9erny2Hvjf2AxHRc=";
    };
  }
]
