name: Release CV

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-cv:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Use Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build CV
        run: |
          nix build .#cv --accept-flake-config
          cp result cv.pdf

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v${{ github.run_number }}'
          files: cv.pdf
